# first check if coupon exists and is available
mutation Mutation($data: CouponPivotCreateInput!) {
    createCouponPivot(data: $data) {
        id
    }
}

# variable here:
# {
#   "data": {
#     "status": null,
#     "customer": {
#       "connect": {
#         "id": "clb1w0tol0014d0loon9kk5n6"
#       }
#     },
#     "couponCode": {
#       "connect": {
#         "id": "clcuazkb30048jglof25krj2v"
#       }
#     }
#   }
# }
