query categoriesWithCategories(
  $id: ID = "dGVybToxNDM="
  $first: Int = 10
  $language: LanguageCodeEnum = EN
) {
  category(id: $id, idType: ID) {
    id
    name
    description
    cat_cf {
      image {
        id
        srcSet(size: MEDIUM)
        sourceUrl
      }
    }
    children(first: $first) {
      edges {
        node {
          id
          name
          description
          cat_cf {
            image {
              altText
              sourceUrl
            }
          }
          translation(language: $language) {
            id
          }
        }
      }
    }
  }
}
