query ChildCategoriesBySlug(
  $id: ID = "dGVybToxNg=="
  $language: LanguageCodeEnum = FA
  $isChildCategory: Boolean = true
  $isChildPage: Boolean = false
) {
  category(id: $id, idType: ID) {
    id
    contentNodes(first: 10) @skip(if: $isChildCategory) {
      nodes {
        id
        ... on Page @include(if: $isChildPage) {
          id
          title
          content
          featuredImage {
            node {
              id
              sourceUrl
              altText
            }
          }
          translation(language: $language) {
            id
          }
        }
      }
    }
    children(first: 10) @include(if: $isChildCategory) {
      edges {
        node {
          id
          name
          description
          cat_cf {
            image {
              id
              sourceUrl
            }
          }
          translation(language: $language) {
            id
          }
        }
      }
    }
    translation(language: $language) {
      id
    }
  }
}
