query Home(
  $languages: [LanguageCodeEnum!] = FA
  $aboutid: ID = "cG9zdDoxMzQ="
) {
  categories(
    where: {
      slug: ["products", "products-fa", "services", "services-fa"]
      languages: $languages
    }
  ) {
    edges {
      node {
        id
        name
        description
        cat_cf {
          image {
            id
            sourceUrl
            srcSet
          }
        }
      }
    }
  }
  page(id: $aboutid) {
    id
    title
    content(format: RENDERED)
    featuredImage {
      node {
        id
        altText
        sourceUrl
        srcSet
      }
    }
  }
}
