query Page(
  $id: ID = "cG9zdDoy"
  $idType: PageIdType = ID
  $language: LanguageCodeEnum = EN
) {
  page(id: $id, idType: $idType) {
    id
    title
    content(format: RENDERED)
    featuredImage {
      node {
        id
        sourceUrl
        altText
      }
    }
    translation(language: $language) {
      id
    }
  }
}
