query product($id: ID = "cG9zdDo2OA==", $language: LanguageCodeEnum = EN) {
  post(id: $id) {
    id
    uri
    title(format: RENDERED)
    slug
    featuredImage {
      node {
        id
        srcSet
        altText
        sourceUrl
      }
    }
    template {
      ... on Template_Product {
        templateName
        cf {
          fieldGroupName
          map {
            id
            sourceUrl
          }
          table {
            id
            mediaItemUrl
          }
        }
      }
    }
    content
    translation(language: $language) {
      id
    }
  }
}
