query CartByUser($user: ID!) {
  carts(
    where: {
      isCompleted: { equals: false }
      AND: [{ user: { id: { equals: $user } } }]
    }
  ) {
    id
    totalPrice
    items {
      id
      priceWithDiscount
      type
      coupon {
        id
        code
        discount
      }
      course {
        id
        name
        priceFa
        price
        image{
          id
          url
        }
      }
      event {
        id
        name
        price
        priceFa
        image{
          id
          url
        }
      }
    }
  }
}
