query course($id: ID!) {
  course(where: { id: $id }) {
    id
    name
    description
    teacher {
      name
      description
      image {
        id
        url
      }
    }
    image {
      id
      url
    }
    rate
    comments(orderBy: { createdAt: desc }) {
      id
      user {
        id
        name
        lastName
      }
      comment
      rate
      createdAt
    }
    commentsCount
    courseItem {
      id
      no
      name
      description
    }
  }
}
