query course($id: ID!) {
  course(where: { id: $id }) {
    id
    name
    description
    teacher {
      name
      description
      image {
        id
        url
      }
    }
    image {
      id
      url
    }
    rate
    commentsCount
    courseItem {
      id
      no
      name
      description
    }
  }
}
