query courses {
  courses {
    id
    name
    description
    isAccessible
    image {
      id
      url
    }
    price
    teacher {
      name
      image {
        id
        url
      }
      id
    }
  }
}
