query events {
  events {
    id
    name
    from
    to
    description
    price
    priceFa
    status
    isAccessible
    isUpcomming
    isOpen
    remaining
    image {
      id
      url
    }
  }
}
