query event($id: ID!) {
  event(where: { id: $id }) {
    id
    name
    content {
      document
    }
    from
    to
    description
    location
    price
    priceFa
    status
    isAccessible
    isUpcomming
    isOpen
    remaining
    image {
      id
      url
    }
  }
}
