query myCourses($id: ID!) {
  user(where: { id: $id }) {
    courses {
      id
      name
      rate
      commentsCount
      image {
        url
      }
      teacher {
        id
        name
        image {
          url
        }
      }
    }
  }
}
