query userCommentAndRate($userId: ID!, $courseId: ID!) {
  comments(
    where: {
      user: { id: { equals: $userId } }
      course: { id: { equals: $courseId } }
    }
  ) {
    rate
    comment
    id
  }
}
